import streamlit as st
import pandas as pd
import plotly.express as px


def render(executive, fact_sales, dim_store, dim_product, selected_store):
    # Product & Sales Intelligence
    # --------------------------------------

    st.markdown(
        '<div class="executive-container">',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="section-kicker">SECTION 3 OF 6</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="section-title">Product & Sales Intelligence</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="section-question">What products drive it?</div>',
        unsafe_allow_html=True,
    )

    product_store_data = (
        fact_sales[fact_sales["store_id"] == selected_store]
        .groupby("item_id")
        .agg(
            revenue=("revenue", "sum"),
            units_sold=("units_sold", "sum"),
        )
        .reset_index()
    )

    product_store_data = product_store_data.merge(
        dim_product[["item_id", "dept_id", "cat_id"]],
        on="item_id",
        how="left",
    )

    product_store_data["avg_selling_price"] = (
        product_store_data["revenue"] /
        product_store_data["units_sold"].replace(0, pd.NA)
    )

    product_store_data = product_store_data.sort_values(
        "revenue",
        ascending=False,
    ).reset_index(drop=True)

    product_store_data["revenue_rank"] = (
        product_store_data.index + 1
    )

    product_store_data["revenue_share"] = (
        product_store_data["revenue"] /
        product_store_data["revenue"].sum() * 100
    )

    top_product = (
        product_store_data.iloc[0]
        if not product_store_data.empty
        else None
    )

    top_product_id = (
        top_product["item_id"]
        if top_product is not None
        else "N/A"
    )

    top_product_revenue = (
        top_product["revenue"]
        if top_product is not None
        else 0
    )

    top_product_units = (
        top_product["units_sold"]
        if top_product is not None
        else 0
    )

    active_product_count = len(product_store_data)

    category_sales = (
        product_store_data
        .groupby("cat_id")
        .agg(
            revenue=("revenue", "sum"),
            units_sold=("units_sold", "sum"),
        )
        .reset_index()
        .sort_values("revenue", ascending=False)
    )

    top_category = (
        category_sales.iloc[0]["cat_id"]
        if not category_sales.empty
        else "N/A"
    )

    # KPI cards
    p1, p2, p3, p4 = st.columns(4)

    with p1:
        st.markdown(
            f"""
            <div class="kpi-card kpi-revenue">
                <div class="kpi-icon">🏆</div>
                <div class="kpi-label">Top Product</div>
                <div class="kpi-value">{top_product_id}</div>
                <div class="kpi-note">Highest revenue at {selected_store}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with p2:
        st.markdown(
            f"""
            <div class="kpi-card kpi-units">
                <div class="kpi-icon">💰</div>
                <div class="kpi-label">Top Product Revenue</div>
                <div class="kpi-value">${top_product_revenue:,.0f}</div>
                <div class="kpi-note">Revenue generated by top product</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with p3:
        st.markdown(
            f"""
            <div class="kpi-card kpi-products">
                <div class="kpi-icon">📦</div>
                <div class="kpi-label">Active Products</div>
                <div class="kpi-value">{active_product_count:,}</div>
                <div class="kpi-note">Products sold at {selected_store}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with p4:
        st.markdown(
            f"""
            <div class="kpi-card kpi-risk">
                <div class="kpi-icon">📊</div>
                <div class="kpi-label">Leading Category</div>
                <div class="kpi-value">{top_category}</div>
                <div class="kpi-note">Highest revenue category</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # Product charts
    product_left, product_right = st.columns(2)

    with product_left:

        st.markdown(
            """
            <div class="chart-card">
                <div class="chart-title">Top Products by Revenue</div>
                <div class="chart-subtitle">
                    Products contributing the most revenue at the selected store
                </div>
            """,
            unsafe_allow_html=True,
        )

        top_products_revenue = product_store_data.head(10).sort_values(
            "revenue"
        )

        revenue_product_chart = px.bar(
            top_products_revenue,
            x="revenue",
            y="item_id",
            orientation="h",
        )

        revenue_product_chart.update_traces(marker_line_width=0)

        revenue_product_chart.update_layout(
            height=390,
            margin=dict(l=10, r=25, t=15, b=10),
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#60758d"),
            showlegend=False,
        )

        revenue_product_chart.update_xaxes(
            showgrid=True,
            gridcolor="#edf2f7",
            title=None,
            tickprefix="$",
            tickformat=",.0f",
        )

        revenue_product_chart.update_yaxes(
            title=None,
            showgrid=False,
        )

        st.plotly_chart(
            revenue_product_chart,
            use_container_width=True,
            config={"displayModeBar": False},
        )

        st.markdown("</div>", unsafe_allow_html=True)

    with product_right:

        st.markdown(
            """
            <div class="chart-card">
                <div class="chart-title">Top Products by Units</div>
                <div class="chart-subtitle">
                    Highest-demand products at the selected store
                </div>
            """,
            unsafe_allow_html=True,
        )

        top_products_units = (
            product_store_data
            .sort_values("units_sold", ascending=False)
            .head(10)
            .sort_values("units_sold")
        )

        units_product_chart = px.bar(
            top_products_units,
            x="units_sold",
            y="item_id",
            orientation="h",
        )

        units_product_chart.update_traces(marker_line_width=0)

        units_product_chart.update_layout(
            height=390,
            margin=dict(l=10, r=25, t=15, b=10),
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#60758d"),
            showlegend=False,
        )

        units_product_chart.update_xaxes(
            showgrid=True,
            gridcolor="#edf2f7",
            title=None,
            tickformat=",.0f",
        )

        units_product_chart.update_yaxes(
            title=None,
            showgrid=False,
        )

        st.plotly_chart(
            units_product_chart,
            use_container_width=True,
            config={"displayModeBar": False},
        )

        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Category sales mix
    category_left, category_right = st.columns([1, 1.4])

    with category_left:

        st.markdown(
            """
            <div class="chart-card">
                <div class="chart-title">Product Category Mix</div>
                <div class="chart-subtitle">
                    Revenue contribution by category
                </div>
            """,
            unsafe_allow_html=True,
        )

        category_chart = px.pie(
            category_sales,
            names="cat_id",
            values="revenue",
            hole=0.58,
        )

        category_chart.update_traces(
            textposition="inside",
            textinfo="percent",
        )

        category_chart.update_layout(
            height=350,
            margin=dict(l=10, r=10, t=15, b=10),
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(color="#60758d"),
        )

        st.plotly_chart(
            category_chart,
            use_container_width=True,
            config={"displayModeBar": False},
        )

        st.markdown("</div>", unsafe_allow_html=True)

    with category_right:

        st.markdown(
            """
            <div class="chart-card">
                <div class="chart-title">Product Performance Detail</div>
                <div class="chart-subtitle">
                    Revenue, demand, and revenue share by product
                </div>
            """,
            unsafe_allow_html=True,
        )

        product_table = product_store_data.head(10).copy()
        product_table["revenue_share"] = product_table["revenue_share"].round(2)
        product_table["revenue"] = product_table["revenue"].round(2)

        st.dataframe(
            product_table[
                [
                    "revenue_rank",
                    "item_id",
                    "cat_id",
                    "units_sold",
                    "revenue",
                    "revenue_share",
                ]
            ],
            use_container_width=True,
            hide_index=True,
            column_config={
                "revenue_rank": "Rank",
                "item_id": "Product ID",
                "cat_id": "Category",
                "units_sold": "Units Sold",
                "revenue": st.column_config.NumberColumn(
                    "Revenue",
                    format="$%,.2f",
                ),
                "revenue_share": st.column_config.NumberColumn(
                    "Revenue Share %",
                    format="%.2f%%",
                ),
            },
            height=350,
        )

        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Product insight
    st.markdown(
        f"""
        <div class="info-box">
            <div class="info-title">💡 Product Insight</div>
            <b>{top_product_id}</b> is the highest-revenue product at
            <b>{selected_store}</b>, generating
            <b>${top_product_revenue:,.2f}</b> from
            <b>{top_product_units:,.0f}</b> units sold. The next step is to
            connect these high-performing products with demand forecasts and
            inventory risk to determine whether supply should be adjusted.
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("</div>", unsafe_allow_html=True)


    # --------------------------------------
