# --------------------------------------
# Grok AI Recommendation Engine
# --------------------------------------

import os

from dotenv import load_dotenv
from openai import OpenAI


# --------------------------------------
# Load Environment Variables
# --------------------------------------

load_dotenv()


# --------------------------------------
# Create Grok Client
# --------------------------------------

def get_grok_client():

    api_key = os.getenv("XAI_API_KEY")

    if not api_key:
        raise ValueError(
            "XAI_API_KEY was not found. "
            "Please add your Grok API key to the .env file."
        )

    return OpenAI(
        api_key=api_key,
        base_url="https://api.x.ai/v1",
    )


# --------------------------------------
# Generate Business Recommendation
# --------------------------------------

def generate_grok_recommendation(
    selected_store,
    store_revenue,
    average_store_revenue,
    revenue_gap_pct,
    top_product,
    top_product_revenue,
    priority_item,
    priority_forecast,
    top_risk,
    top_risk_score,
    top_risk_class,
):

    client = get_grok_client()

    prompt = f"""
You are the AI Business Recommendation engine for RetailIQ,
a retail business intelligence and inventory decision-support platform.

Your job is to interpret structured analytics generated by RetailIQ
and provide a concise, practical recommendation for a retail manager.

IMPORTANT RULES:

1. Use only the information provided below.
2. Do not invent numbers, products, stores, or business facts.
3. Do not recalculate the provided metrics.
4. Do not claim that the forecast is guaranteed future demand.
5. The forecast represents a historical 30-day model evaluation period.
6. The inventory-risk score is a RetailIQ decision-support metric.
7. Do not describe the risk score as a probability of stockout.
8. Recommend validation before any operational inventory change.
9. Keep the recommendation practical and concise.
10. Do not use a markdown table.

RETAILIQ BUSINESS SIGNALS

Selected Store:
{selected_store}

Selected Store Revenue:
${store_revenue:,.2f}

Average Store Revenue:
${average_store_revenue:,.2f}

Store Revenue Difference:
{revenue_gap_pct:.1f}%

Top Product at Selected Store:
{top_product}

Top Product Revenue:
${top_product_revenue:,.2f}

Priority Product:
{priority_item}

Evaluated 30-Day Forecast:
{priority_forecast:,.0f} units

Highest Inventory-Risk Product:
{top_risk}

Highest Inventory-Risk Score:
{top_risk_score:.4f}

ABC Class:
{top_risk_class}

TASK

Act as a business analyst.

Explain the most important business signal and recommend
what the retail manager should consider doing.

Return exactly these four sections:

KEY SIGNAL

RECOMMENDATION

WHY

VALIDATE BEFORE ACTION

Under "VALIDATE BEFORE ACTION", provide 2 or 3 short checks.

Keep the entire response concise and professional.
"""

    response = client.responses.create(
        model="grok-4.7",
        input=prompt,
    )

    return response.output_text